experiment_id: custom_experiment_1
number_of_dags: 1
min_tasks_per_dag: 1

# Schedules and weights
schedules:
  "@daily": 1

# Start dates and weights
start_dates:
  "9/24/2024": 1

# 27000
# taskflows and weights
taskflows:
  custom:
    CustomDataPipeline: 1

# Default settings for every generated DAG.
default_settings:
  project_id: cy-artifacts 
  region: us-central1
  composer_environment: composer-3-load-testing
  deferrable: true
  retries: 1
  retry_delay: 2 # minutes
  catchup: false
  is_paused_upon_creation: false
  dagrun_timeout: 60 # minutes
  execution_timeout: 30 # minutes
  sla: 25 # minutes
  mode: poke
  poke_interval: 120 # seconds