experiment_id: experiment_4
number_of_dags: 1800
min_tasks_per_dag: 7

# Schedules and weights
schedules:
  "@daily": 0.5
  "10 * * * *": 0.1
  "20 * * * *": 0.1
  "30 * * * *": 0.1
  "40 * * * *": 0.1
  "50 * * * *": 0.1

# Start dates and weights
start_dates:
  "9/20/2024": 1

# 27000
# taskflows and weights
taskflows:
  base:
    EmptyOperator: 0.3
    PythonOperator: 0.26
    BashOperator: 0.05
    BranchPythonOperator: 0.05
    KubernetesPodOperator: 0
  google_cloud:
    BigQueryInsertJobOperator: 0.22
    DataprocCreateBatchOperator: 0.05
    GCSToBigQueryOperator: 0.03
    DataprocSubmitJobOperator: 0
    BeamRunJavaPipelineOperator: 0
    GCSToGCSOperator: 0
    GKEStartPodOperator: 0
    # sensor taskflows

# Default settings for every generated DAG.
default_settings:
  deferrable: true
  retries: 1
  retry_delay: 2 # minutes
  catchup: false
  is_paused_upon_creation: false
  dagrun_timeout: 60 # minutes
  execution_timeout: 30 # minutes
  sla: 25 # minutes
  project_id: cy-artifacts
  region: us-central1
  mode: poke
  poke_interval: 120 # seconds