experiment_id: experiment_1
number_of_dags: 10
tasks_per_dag: 3

# Schedules and weights
schedules:
  "@daily": 0.5
  "0 * * * *": 0.1
  "10 * * * *": 0.1
  "20 * * * *": 0.1
  "30 * * * *": 0.1
  "40 * * * *": 0.1

# Start dates and weights
start_dates:
  "9/19/2024": 1

# taskflows and weights
taskflows:
  base:
    PythonOperator: 0.3
    KubernetesPodOperator: 0.3
    BashOperator: 0.3
    EmptyOperator: 0.3
    BranchPythonOperator: 0.3
  google_cloud:
    BigQueryInsertJobOperator: 0.001
    DataprocSubmitJobOperator: 0.001
    BeamRunJavaPipelineOperator: 0.001
    DataprocCreateBatchOperator: 0.001
    GCSToGCSOperator: 0.001
    GCSToBigQueryOperator: 0.001
    GKEStartPodOperator: 0.001

# Default settings for every generated DAG.
default_settings:
  deferrable: true
  retries: 1
  catchup: false
  is_paused_upon_creation: false
  execution_timeout: 30
  sla: 25
  project_id: cy-artifacts
  region: us-central1
  mode: poke
  poke_interval: 120